language: node_js

node_js:
  - "stable"
script: npm run $COMMAND
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 5"

env:
  matrix:
  - COMMAND=test
  - COMMAND=coverage

branches:
  only:
  - master
  - /^pull*$/
